from __future__ import annotations

TRACKING_TARGET = "near_plate_collar_center"
TRACKING_SOURCE = "opencv_circle_tracker"
BARBELL_TRACK_TARGET_FPS = 18.0
MAX_DETECTION_CROP_WIDTH = 240
MAX_CANDIDATES_PER_FRAME = 12
MIN_TRACK_COVERAGE = 0.2
MIN_TRACK_POINTS = 4
MAX_INTERPOLATION_GAP_FRAMES = 6
COLLAR_OFFSET_RATIO = 0.28
MIN_COLLAR_OFFSET_RATIO = 0.1
MAX_COLLAR_OFFSET_RATIO = 0.35
DEFAULT_SLEEVE_DIRECTION = (0.996, -0.09)
COLLAR_REFINEMENT_AXIS_DEGREES = 30.0
COLLAR_REFINEMENT_DISTANCE_CAP_RATIO = 0.5
COLLAR_GEOMETRIC_FALLBACK_CONFIDENCE_PENALTY = 0.15
INIT_CONFIRMATION_FRAMES = 3
MAX_LOCAL_TRACKING_FAILURES = 2
MAX_OUTLIER_VELOCITY = 0.22
